per_page: 10
max_name: 30
min_password: 6
defaul_avatar: "default_user.png"
view_detail: "Một hoạt động sắp diễn ra!!! xem chi tiết tại: "
club_request_admin: "A request create club has been sent to you"
event_request_admin: "A request create event has been sent to you"
